---
abstract: 'a simple way to receive and handle structured messages via UDP'
author:
  - 'Robin Smidsrød <robin@smidsrod.no>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.87'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-UDP-Server
no_index:
  directory:
    - inc
    - t
requires:
  Data::Serializable: 0
  IO::Socket::INET: 0
  MooseX::POE: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
